#pragma config(Sensor, in1,    lightRPM,       sensorLineFollower)
#pragma config(Sensor, dgtl1,  rpmSensor,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rpmReady,       sensorDigitalOut)
#pragma config(Motor,  port1,           RightCon,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           RightDriveFront, tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           RightDriveBack, tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           fly1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           fly2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           fly3,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           fly4,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LeftDriveBack, tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           LeftDriveFront, tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port10,          LeftCon,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <Setup.h>
#include <Movement.h>

task main()
{
	SensorValue[rpmReady] = 0;
	resetSlewArray();
	Conveyor(127);
	startTask(RPM);
	//FlywheelPower(100);
	wait10Msec(100);
	startTask(FlywheelController);
	while(true){}
}
