#pragma config(Sensor, dgtl1,  rpmSensor,      sensorQuadEncoder)
#pragma config(Motor,  port1,           RightCon,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           RightDriveFront, tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           RightDriveBack, tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           RightFlyDown,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RightFlyUp,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           LeftFlyUp,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LeftFlyDown,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LeftDriveBack, tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           LeftDriveFront, tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port10,          LeftCon,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float currentRPM = 0;
task rpm()
{
	int y1 = 0;
	int y2 = 0;
	int waitTime = 100;
	while(true)
	{
		y2 = SensorValue[rpmSensor];
		currentRPM = (((y2-y1)/360.0)/(waitTime/60000.0));
		y1 = y2;
		wait1Msec(waitTime);
	}
}

task main()
{
	motor[RightCon] = motor[LeftCon] = 127;
	motor[RightFlyUp] = motor[RightFlyDown] = motor[LeftFlyUp] = motor[LeftFlyDown] = 127;
	startTask(rpm);
}
