#pragma config(Sensor, in1,    lightRPM,       sensorLineFollower)
#pragma config(Sensor, dgtl1,  rpmReady,       sensorDigitalOut)
#pragma config(Sensor, dgtl2,  rpmNotReady,    sensorDigitalOut)
#pragma config(Sensor, dgtl10, rpmSensor,      sensorQuadEncoder)
#pragma config(Sensor, dgtl12, shotsFired,     sensorDigitalIn)
#pragma config(Motor,  port1,           RightCon,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RightDriveFront, tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           RightDriveBack, tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           fly1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           fly2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           fly3,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           fly4,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LeftDriveBack, tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           LeftDriveFront, tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port10,          LeftCon,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int driverTarget = 2650;
#include <Movement.h>
#include <Skills.h>

void setUp()
{
	//resetSlewArray();
	SensorValue[rpmReady] = 1;
	SensorValue[rpmNotReady] = 1;
	SensorValue[rpmSensor] = 0;
	startTask(rpmIndicator);
}

task main()
{
	setUp();
	Conveyor(127);
	startTask(FlywheelController);
	startTask(recoverFromShots);
	SetTarget(2200,50);
	while(true)
	{
		wait1Msec(10);
	}
}
